
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfDocument;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.String;
import java.awt.Color;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akshay Bali
 */
public class BILLING extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
   BILLING(String c_name, String mobile, String emp_name,String emp_id) {
       initComponents();
    //   combo();
ccno.setText(mobile);
cname.setText(c_name);
empname.setText(emp_name);
empmob.setText(emp_id);
   combo();
   }
    public BILLING() {
        initComponents();
           combo(); 
    }
  
    
 
    public void combo()
{    
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from product";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                ppname.addItem(type_r1.getString(3));   

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        no_row = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        count = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        grandtotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        couponname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        netpay = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        discountamount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ccno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        empname = new javax.swing.JTextField();
        ppname = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        empmob = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        CUST2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        BILL2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BILL3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BILLING:");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ROW_NO.", "product_id", "name", "count", "UNIT_PRICE", "TOTAL PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pid.setBackground(new java.awt.Color(204, 204, 204));
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PRODUCT ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ENTER COUNT:");

        count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        grandtotal.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("GRAND TOTAL:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("COUPON CODE:");

        couponname.setEditable(false);
        couponname.setText("no value");

        jButton2.setText("APPLY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("NET PAYABLE AMOUNT:");

        jButton3.setText("GENERATE BILL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("ENTER PRODUCT name:");

        jButton4.setText("REMOVE SELECTED ROW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setText("ENTER ROW NO. TO REMOVE:");

        jButton5.setText("GENERATE TOTAL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("DISCOUNT AMOUNT:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Customer Name:");

        cname.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Mobile No.:");

        ccno.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Handled By Employee:");

        empname.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("EMPLOYEE MOBILE:");

        empmob.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(discountamount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grandtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(couponname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(netpay, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jButton3))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ppname, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ccno, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(empname))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empmob, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ppname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grandtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(couponname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(discountamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(45, 45, 45))
        );

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        CUST2.setBackground(new java.awt.Color(204, 0, 204));
        CUST2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CUST2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CUST2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CUST2MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CUSTOMER DETAILS.");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout CUST2Layout = new javax.swing.GroupLayout(CUST2);
        CUST2.setLayout(CUST2Layout);
        CUST2Layout.setHorizontalGroup(
            CUST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CUST2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );
        CUST2Layout.setVerticalGroup(
            CUST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CUST2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        BILL2.setBackground(new java.awt.Color(204, 0, 204));
        BILL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BILL2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BILL2MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BILLING.");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BILL2Layout = new javax.swing.GroupLayout(BILL2);
        BILL2.setLayout(BILL2Layout);
        BILL2Layout.setHorizontalGroup(
            BILL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BILL2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        BILL2Layout.setVerticalGroup(
            BILL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BILL2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        BILL3.setBackground(new java.awt.Color(204, 0, 204));
        BILL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BILL3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BILL3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BILL3MouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Log out");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BILL3Layout = new javax.swing.GroupLayout(BILL3);
        BILL3.setLayout(BILL3Layout);
        BILL3Layout.setHorizontalGroup(
            BILL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BILL3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        BILL3Layout.setVerticalGroup(
            BILL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BILL3Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CUST2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BILL2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(BILL3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CUST2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BILL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BILL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        //jLabel8.setOpaque(true);        // TODO add your handling code here:
        //jLabel1.setForeground(Color.getHSBColor(255,255,255));
        // jLabel8.setForeground(Color.getHSBColor(51,0,51));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // jLabel8.setForeground(Color.getHSBColor(204,0,204));
        //jLabel8.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void CUST2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUST2MouseEntered
        CUST2.setOpaque(true);        // TODO add your handling code here:
        CUST2.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_CUST2MouseEntered

    private void CUST2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUST2MouseExited
        CUST2.setForeground(Color.getHSBColor(204, 0, 204));
        CUST2.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_CUST2MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void BILL2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILL2MouseEntered
        BILL2.setOpaque(true);        // TODO add your handling code here:
        //jLabel1.setForeground(Color.getHSBColor(255,255,255));
        BILL2.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_BILL2MouseEntered

    private void BILL2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILL2MouseExited
        BILL2.setForeground(Color.getHSBColor(204, 0, 204));
        BILL2.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BILL2MouseExited

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        //jLabel1.setForeground(Color.black);
        //jLabel1.setOpaque(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        //jLabel1.setOpaque(true);        // TODO add your handling code here:
        //jLabel1.setForeground(Color.getHSBColor(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseMoved
int row=1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String p_name = (String) ppname.getSelectedItem();
        String c_no=ccno.getText();
        String emp_no=empmob.getText();
        String p_id_s;
        int p_id;//=Integer.parseInt(pid.getText());
        int p_count = Integer.parseInt((count.getText()));
        //int p_count=Integer.parseInt(p_count_s);
        int p_available,p_sold;
        int p_price = 0;
        //String pid1;
        int total,p1,gt;
        String grandtotal1;
        grandtotal1=grandtotal.getText();
        gt=Integer.parseInt(grandtotal1);
        //int count=Integer.parseInt(p_count);
       
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            
            
            String NAME_CHECK="select * from product where p_name=?";  
            PreparedStatement NAME_Statement= con.prepareStatement(NAME_CHECK);
            NAME_Statement.setString(1,p_name);
            ResultSet ks=NAME_Statement.executeQuery();
            if(ks.next())
            {    
                p_id=ks.getInt("p_id");
                p_id_s=Integer.toString(p_id);
                pid.setText(p_id_s);
                p_price=ks.getInt("p_price");
               // p_count=(ks.getInt("p_count"));
                p_available=ks.getInt("available_stock");
                p_sold=ks.getInt("sold_stock");
                if(p_available-p_count>0)
                {
                    p_available=p_available-p_count;
                    p_sold=p_sold+p_count;
                    String query3="update product set available_stock=?,sold_stock=? where p_id=?";
                    PreparedStatement pst = con.prepareStatement(query3);
                    pst.setInt(3,p_id);
                    pst.setInt(1,p_available);
                    pst.setInt(2,p_sold);
                    pst.executeUpdate();
                
                    String bill_CHECK="select * from billing where p_id=?";  
                    PreparedStatement bill_Statement= con.prepareStatement(bill_CHECK);
                    bill_Statement.setInt(1,p_id);
                    ResultSet bill_result=bill_Statement.executeQuery();
                    if(bill_result.next())
                    {    
                        p_price=bill_result.getInt("p_price");
        
                        String update_query="update billing set p_count=p_count+?,total_price=total_price+? where p_id=?";
                        PreparedStatement bill_statement = con.prepareStatement(update_query);
                        bill_statement.setInt(3,p_id);
                        bill_statement.setInt(1,p_count);
        
                        //p_count=bill_result.getInt("p_count");
                        int tp=p_price*p_count;
                        bill_statement.setInt(2,tp);
                        //p_count=bill_result.getInt("p_count");
                        bill_statement.executeUpdate();
                        total=p_count*p_price;
                    }    
                    else
                    {    
                        String query = "insert into billing(p_id,p_name,p_price,p_count,total_price,c_mobile,emp_mobile)values(?,?,?,?,?,?,?)";
                        PreparedStatement preparedStatement1 = con.prepareStatement(query);
                        preparedStatement1.setInt(1,p_id);
                        preparedStatement1.setString(2,p_name);
                        preparedStatement1.setInt(3,p_price);
                        preparedStatement1.setInt(4,p_count);
                        total=p_count*p_price;
                        preparedStatement1.setInt(5,total);
  
                        preparedStatement1.setString(6,c_no);
                        preparedStatement1.setString(7,emp_no);
                
                        preparedStatement1.executeUpdate();
                    }
                    DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
                    model.addRow(new Object[]{row,p_id,p_name,p_count,p_price,total});
                    row=row+1;
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Product is out of stock please update the system stock!!");
                }
            }             
            con.close();
            
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CUST2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUST2MouseClicked
                        //String cno=ccno.getText();
                        this.setVisible(false);
                        new CUSTOMER_DETAILS().setVisible(true);
//                        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_CUST2MouseClicked

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1PropertyChange
int i=0;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String c_name=cname.getText();
String mobile=ccno.getText();
String emp_name=empname.getText();
        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
      try
      {
   PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("C:\\akshay\\mega-mart\\bill"+mobile+".pdf"));
   i++;     
   document.open();
          document.addTitle("BILLING");
          //addEmptyLine(preface,8);
          Paragraph preface = new Paragraph();
          //addEmptyLine(preface,1);
             for (int i = 0; i < 1; i++) {
            preface.add(new Paragraph(" "));
             }
          preface.add(new Paragraph("                                                            MEGAMART BILLING"));
          
           
           preface.add(new Paragraph(" "));
           preface.add(new Paragraph("Customer Name : "+c_name));
           preface.add(new Paragraph(" "));
           preface.add(new Paragraph("Customer Contact : "+mobile));
           preface.add(new Paragraph(" "));
           preface.add(new Paragraph("Handled By Employee : "+emp_name));
           preface.add(new Paragraph(" "));
          
           document.add(preface);
           
           PdfPTable table = new PdfPTable(4); // 3 columns.
          table.setWidthPercentage(100); //Width 100%
          table.setSpacingBefore(10f); //Space before table
          table.setSpacingAfter(10f); //Space after table

          //Set Column widths
          float[] columnWidths = {1f, 1f, 1f, 1f};
          table.setWidths(columnWidths);


          
          
          
          PdfPCell cell1 = new PdfPCell(new Paragraph("Product Name"));
          cell1.setBorderColor(BaseColor.BLACK);
          cell1.setPaddingLeft(10);
          cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell1.setVerticalAlignment(Element.ALIGN_MIDDLE);

          PdfPCell cell2 = new PdfPCell(new Paragraph("Product Price"));
          cell2.setBorderColor(BaseColor.BLACK);
          cell2.setPaddingLeft(10);
          cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell2.setVerticalAlignment(Element.ALIGN_MIDDLE);

          PdfPCell cell3 = new PdfPCell(new Paragraph("Product Count"));
          cell3.setBorderColor(BaseColor.BLACK);
          cell3.setPaddingLeft(10);
          cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell3.setVerticalAlignment(Element.ALIGN_MIDDLE);
          
          PdfPCell cell4 = new PdfPCell(new Paragraph("Total Cost"));
          cell4.setBorderColor(BaseColor.BLACK);
          cell4.setPaddingLeft(10);
          cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell4.setVerticalAlignment(Element.ALIGN_MIDDLE);

          //To avoid having the cell border and the content overlap, if you are having thick cell borders
          //cell1.setUserBorderPadding(true);
          //cell2.setUserBorderPadding(true);
          //cell3.setUserBorderPadding(true);
          

          table.addCell(cell1);
          table.addCell(cell2);
          table.addCell(cell3);
          table.addCell(cell4);
          
        try{
                        Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");

            PreparedStatement pst;
            String sql ="SELECT * FROM billing where c_mobile=?;";
            pst = con.prepareStatement(sql);
            pst.setString(1,mobile);
          
            ResultSet rs = pst.executeQuery(); // without arguments
            
            while(rs.next())  
            {
                System.out.println("name : "+rs.getString("p_name"));
                System.out.println("id : "+rs.getString("p_id"));
                System.out.println("cost : "+rs.getString("p_price"));
                PdfPCell cellI = new PdfPCell(new Paragraph(rs.getString("p_name")));
                cellI.setBorderColor(BaseColor.BLACK);
                cellI.setPaddingLeft(10);
                cellI.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellI.setVerticalAlignment(Element.ALIGN_MIDDLE);
                
                PdfPCell cellJ = new PdfPCell(new Paragraph(rs.getString("p_price")));
                cellJ.setBorderColor(BaseColor.BLACK);
                cellJ.setPaddingLeft(10);
                cellJ.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellJ.setVerticalAlignment(Element.ALIGN_MIDDLE);
                
                PdfPCell cellK = new PdfPCell(new Paragraph(rs.getString("p_count")));
                cellK.setBorderColor(BaseColor.BLACK);
                cellK.setPaddingLeft(10);
                cellK.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellK.setVerticalAlignment(Element.ALIGN_MIDDLE);
                
                PdfPCell cellM = new PdfPCell(new Paragraph(rs.getString("total_price")));
                cellM.setBorderColor(BaseColor.BLACK);
                cellM.setPaddingLeft(10);
                cellM.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellM.setVerticalAlignment(Element.ALIGN_MIDDLE);

                table.addCell(cellI);
                table.addCell(cellJ);
                table.addCell(cellK);
                table.addCell(cellM);
            
        
            }
            //Section section1;
            document.add(table);
            Paragraph preface1 = new Paragraph();
             for (int i = 0; i < 3; i++) {
            preface1.add(new Paragraph(" "));
             }
             preface1.add(new Paragraph(" "));
             preface1.add(new Paragraph("Total Price        : "+grandtotal.getText()));
             preface1.add(new Paragraph(" "));
             preface1.add(new Paragraph("DISCOUNT           : "+discountamount.getText()));
             preface1.add(new Paragraph(" "));
             preface1.add(new Paragraph("DISCOUNTED Price   : "+netpay.getText()));
             preface1.add(new Paragraph(" "));
             preface1.add(new Paragraph("Net Payable Amount : "+netpay.getText()));
             preface1.add(new Paragraph(" "));
          document.add(preface1);     
                String query61="DELETE from billing";
                PreparedStatement pst11 = con.prepareStatement(query61);
                //pst1.setString(1,name4);
                //pst1.setString(2,name1);
            //preparedStatement.setString(2,pwd);
                pst11.executeUpdate();
            
        }
        catch(Exception e){
            System.out.println(e);
        }
        
         // document.add(table);
        
          document.close();
          writer.close();
          JOptionPane.showMessageDialog(this,"Summary Generated Successfully");  
      } catch (Exception e)
      {
          e.printStackTrace();
           JOptionPane.showMessageDialog(this,e);  
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
//String row_no=no_row.getText();
//int row=Integer.parseInt(row_no);
String p_id,p_count_s;
int id,p_count;
int selectedRowIndex = jTable1.getSelectedRow();
p_id = jTable1.getModel().getValueAt(selectedRowIndex,1).toString();
p_count_s=jTable1.getModel().getValueAt(selectedRowIndex,3).toString();
p_count=Integer.parseInt(p_count_s);
id=Integer.parseInt(p_id);

//System.out.print("p_id= "+p_id);
model.removeRow(selectedRowIndex);
//jTable1.revalidate();
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query5="select * from billing where p_id=?";
            
           PreparedStatement preparedStatement5 = con.prepareStatement(query5);
            preparedStatement5.setInt(1,id);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement5.executeQuery();
            if(rs.next())
            {    
                int add_stock=rs.getInt("p_count");
                int p_price=rs.getInt("p_price");
 String query3="update product set available_stock=available_stock+?,sold_stock=sold_stock-? where p_id=?";
                PreparedStatement pst = con.prepareStatement(query3);
                pst.setInt(1,p_count);
                pst.setInt(2,p_count);
                pst.setInt(3,id);
                pst.executeUpdate();

if(p_count<add_stock)
{
                String query6="update billing set p_count=p_count-?,total_price=total_price-? where p_id=?";
                //String query6="DELETE from billing where p_id=?";
                PreparedStatement pst1 = con.prepareStatement(query6);
                pst1.setInt(1,p_count);
                int tp=p_count*p_price;
                pst1.setInt(2,tp);
                pst1.setInt(3,id);
//pst1.setString(2,name1);
            //preparedStatement.setString(2,pwd);
                pst1.executeUpdate();

                JOptionPane.showMessageDialog(this,"ID DETAILS DELETED!!");
}
else
{
            String query7="DELETE from billing where p_id=?";
                PreparedStatement pst2 = con.prepareStatement(query7);
                pst2.setInt(1,id);
                pst2.executeUpdate();

                JOptionPane.showMessageDialog(this,"ID DETAILS DELETED!!");
    
}
}
            else
            {
            
                JOptionPane.showMessageDialog(this,"LOGIN ID ENTERED NOT PRESENT IN DATABASE!!");  
      
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }

        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String mobile=ccno.getText();
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query2="select sum(total_price) from billing";
            
           PreparedStatement preparedStatement = con.prepareStatement(query2);
            
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {    
                int gt=rs.getInt("sum(total_price)");
                String gt1=Integer.toString(gt);
                grandtotal.setText(gt1);
            String custom_CHECK="select * from customer where mobile=?";

                PreparedStatement custom_Statement= con.prepareStatement(custom_CHECK);
                custom_Statement.setString(1,mobile);
                //coupon_Statement.setInt(2,total_shopping);
                ResultSet custom_Result=custom_Statement.executeQuery();
            int visits=0,shopping=0;
                if(custom_Result.next())
                {
                     visits = Integer.parseInt(custom_Result.getString("no_of_visits"));
                     shopping = Integer.parseInt(custom_Result.getString("total_shopping"));
                }
                else{
                    visits=0;
                shopping=0;
                }
                String coupon_CHECK="select * from coupons where no_of_visits=? and total_shopping>=?";
                PreparedStatement coupon_Statement= con.prepareStatement(coupon_CHECK);
                coupon_Statement.setInt(1,visits);
                coupon_Statement.setInt(2,shopping);
                ResultSet coupon_Result=coupon_Statement.executeQuery();
            
                if(coupon_Result.next())
                {
                    String coupon_name = coupon_Result.getString("coupon_name");
                    couponname.setText(coupon_name);
                }
                else
                    couponname.setText("no value");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Bill has not been generated!!");  
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }

                                          

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String coupon_name=couponname.getText();
int off_price=0;
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
           String query2="select sum(total_price) from billing";
            
           PreparedStatement preparedStatement = con.prepareStatement(query2);
            
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {    
                int gt=rs.getInt("sum(total_price)");
           
                 String query3="select * from coupons where coupon_name=?";
            
           PreparedStatement preparedStatement1 = con.prepareStatement(query3);
            
            preparedStatement1.setString(1,coupon_name);
            ResultSet rs1=preparedStatement1.executeQuery();
           if(rs1.next())
           {
             
               off_price=rs1.getInt("off_price");
               String off_price_s;
                    off_price_s = Integer.toString(off_price);
             discountamount.setText(off_price_s);
               gt=gt-off_price;
            String gt1=Integer.toString(gt);
            netpay.setText(gt1);
            //JOptionPane.showMessageDialog(this,"!!");

           }
           else
           {
               //int off_price1=rs1.getInt("off_price");
              //String off_price_s = Integer.toString(off_price1);
             discountamount.setText("0");
            String gt1=Integer.toString(gt); 
             netpay.setText(gt1);
              
// JOptionPane.showMessageDialog(this,"Invalid Coupon!!");
           }
            }
            else
            {
            
                JOptionPane.showMessageDialog(this,"Bill not Generated!!");  
      
            }
            
            
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countActionPerformed

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseExited

    private void BILL3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILL3MouseEntered
        BILL3.setOpaque(true);        // TODO add your handling code here:
        //jLabel1.setForeground(Color.getHSBColor(255,255,255));
        BILL3.setForeground(Color.getHSBColor(51, 0, 51));        // TODO add your handling code here:
    }//GEN-LAST:event_BILL3MouseEntered

    private void BILL3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILL3MouseExited
        BILL3.setForeground(Color.getHSBColor(204, 0, 204));
        BILL3.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BILL3MouseExited

    private void BILL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILL3MouseClicked
                        this.setVisible(false);
                        new LOGIN().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BILL3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILLING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BILL2;
    private javax.swing.JPanel BILL3;
    private javax.swing.JPanel CUST2;
    private javax.swing.JTextField ccno;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField count;
    private javax.swing.JTextField couponname;
    private javax.swing.JTextField discountamount;
    private javax.swing.JTextField empmob;
    private javax.swing.JTextField empname;
    private javax.swing.JTextField grandtotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField netpay;
    private javax.swing.JTextField no_row;
    private javax.swing.JTextField pid;
    private javax.swing.JComboBox<String> ppname;
    // End of variables declaration//GEN-END:variables

   
    

}
