
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akshay Bali
 */
public class COUPON extends javax.swing.JFrame {

    /**
     * Creates new form COUPON
     */
    public COUPON() {
        initComponents();
        combo();
    }
public void combo()
{    
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from coupons";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                ccname.addItem(type_r1.getString(1));   

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        OP1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        OP2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        OP3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        OP4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        OP5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable21 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        shop = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cname1 = new javax.swing.JTextField();
        ccname = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        OP1.setBackground(new java.awt.Color(204, 0, 204));
        OP1.setForeground(new java.awt.Color(255, 255, 255));
        OP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP1MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADD NEW PRODUCT.");

        javax.swing.GroupLayout OP1Layout = new javax.swing.GroupLayout(OP1);
        OP1.setLayout(OP1Layout);
        OP1Layout.setHorizontalGroup(
            OP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OP1Layout.setVerticalGroup(
            OP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP2.setBackground(new java.awt.Color(204, 0, 204));
        OP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP2MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PRINT DETAILS.");

        javax.swing.GroupLayout OP2Layout = new javax.swing.GroupLayout(OP2);
        OP2.setLayout(OP2Layout);
        OP2Layout.setHorizontalGroup(
            OP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8)
        );
        OP2Layout.setVerticalGroup(
            OP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP3.setBackground(new java.awt.Color(204, 0, 204));
        OP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP3MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EMPLOYEE DETAILS.");

        javax.swing.GroupLayout OP3Layout = new javax.swing.GroupLayout(OP3);
        OP3.setLayout(OP3Layout);
        OP3Layout.setHorizontalGroup(
            OP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP3Layout.setVerticalGroup(
            OP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP4.setBackground(new java.awt.Color(204, 0, 204));
        OP4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP4MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LOG OUT");

        javax.swing.GroupLayout OP4Layout = new javax.swing.GroupLayout(OP4);
        OP4.setLayout(OP4Layout);
        OP4Layout.setHorizontalGroup(
            OP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP4Layout.setVerticalGroup(
            OP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP5.setBackground(new java.awt.Color(204, 0, 204));
        OP5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP5MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADD COUPON.");

        javax.swing.GroupLayout OP5Layout = new javax.swing.GroupLayout(OP5);
        OP5.setLayout(OP5Layout);
        OP5Layout.setHorizontalGroup(
            OP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP5Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP5Layout.setVerticalGroup(
            OP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP5Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OP3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(OP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("COUPONS.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("ENTER COUPON NAME:");

        jButton8.setText("SEARCH DETAILS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTable21.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COUPON NAME", "NO. OF VISITS", "SHOPPING", "DISCOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable21.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable21);

        jButton10.setText("Remove Selected Row");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("NO. OF VISITS:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("COUPON NAME(NEW/OLD):");

        jButton1.setText("CREATE NEW COUPON.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MODIFY EXISTING COUPON.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("REMOVE COUPON.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("SHOPPING:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("DISCOUNT:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("NEW COUPON NAME(ENTER TO UPDATE COUPON NAME):");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ccname, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cname1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8)
                            .addComponent(jButton10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseClicked
        this.setVisible(false);
        new PRODUCT_DETAILS().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP1MouseClicked

    private void OP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseEntered
        OP1.setOpaque(true);        // TODO add your handling code here:
        OP1.setForeground(Color.getHSBColor(51, 0, 51));
    }//GEN-LAST:event_OP1MouseEntered

    private void OP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseExited
                OP1.setForeground(Color.getHSBColor(204, 0, 204));
        OP1.setOpaque(false);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_OP1MouseExited

    private void OP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseClicked
this.setVisible(false);
        new PRINTDETAILS().setVisible(true);
    }//GEN-LAST:event_OP2MouseClicked

    private void OP2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseEntered
        OP2.setOpaque(true);        // TODO add your handling code here:
        OP2.setForeground(Color.getHSBColor(51, 0, 51));
    }//GEN-LAST:event_OP2MouseEntered

    private void OP2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseExited
               OP2.setForeground(Color.getHSBColor(204, 0, 204));
        OP2.setOpaque(false);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_OP2MouseExited

    private void OP3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP3MouseEntered
                OP3.setOpaque(true);        // TODO add your handling code here:
        OP3.setForeground(Color.getHSBColor(51, 0, 51));

    }//GEN-LAST:event_OP3MouseEntered

    private void OP3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP3MouseExited
                OP3.setForeground(Color.getHSBColor(204, 0, 204));
        OP3.setOpaque(false);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_OP3MouseExited

    private void OP4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseClicked
        this.setVisible(false);
        new LOGIN().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP4MouseClicked

    private void OP4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseEntered
                OP4.setOpaque(true);        // TODO add your handling code here:
        OP4.setForeground(Color.getHSBColor(51, 0, 51));

    }//GEN-LAST:event_OP4MouseEntered

    private void OP4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseExited
               OP4.setForeground(Color.getHSBColor(204, 0, 204));
        OP4.setOpaque(false);        // TODO add your handling code here:

    }//GEN-LAST:event_OP4MouseExited

    private void OP5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OP5MouseClicked

    private void OP5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseEntered
                OP5.setOpaque(true);        // TODO add your handling code here:
        OP5.setForeground(Color.getHSBColor(51, 0, 51));
// TODO add your handling code here:
    }//GEN-LAST:event_OP5MouseEntered

    private void OP5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseExited
                OP5.setForeground(Color.getHSBColor(204, 0, 204));
        OP5.setOpaque(false);        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_OP5MouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String coupon_name=(String) ccname.getSelectedItem();
        String no_of_visits;
        String total_shoping;
        String offprice;

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from coupons where coupon_name=?";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            type_Statement1.setString(1,coupon_name);
            ResultSet type_r1=type_Statement1.executeQuery();
            if(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
               no_of_visits=(type_r1.getString("no_of_visits"));
               total_shoping=(type_r1.getString("total_shopping"));
               offprice=(type_r1.getString("off_price"));
              
                    DefaultTableModel model1= (DefaultTableModel)jTable21.getModel();
                    model1.addRow(new Object[]{coupon_name,no_of_visits,total_shoping,offprice});
            }
                else
                {
                    JOptionPane.showMessageDialog(this,"coupon not present in database!!");
                }

                con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DefaultTableModel model= (DefaultTableModel)jTable21.getModel();
        int selectedRowIndex = jTable21.getSelectedRow();
        model.removeRow(selectedRowIndex);
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String c_name = cname.getText();
        int no_of_visits = Integer.parseInt(no.getText());
        int shopping = Integer.parseInt(shop.getText());
        int d = Integer.parseInt(discount.getText());
       
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query1="select  * from coupons where coupon_name=?";
            PreparedStatement p = con.prepareStatement(query1);
            p.setString(1,c_name);
            ResultSet rs=p.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this,"Coupon already present!!");
            }
            else
            {
                String query = "insert into coupons(coupon_name,no_of_visits,total_shopping,off_price)values(?,?,?,?)";
                PreparedStatement preparedStatement1 = con.prepareStatement(query);
                preparedStatement1.setString(1,c_name);
                preparedStatement1.setInt(2,no_of_visits);
                preparedStatement1.setInt(3,shopping);
                preparedStatement1.setInt(4,d);
                preparedStatement1.executeUpdate();
                JOptionPane.showMessageDialog(this,"coupon CREATED SUCCESSFULLY!!");

            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        String coupon_name=cname.getText();
        String coupon_name1=cname1.getText();
        int no_of_visits=Integer.parseInt(no.getText());
        int total_shopping=Integer.parseInt(shop.getText());
        int off_price=Integer.parseInt(discount.getText());
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query2="select * from coupons where coupon_name=?";
            
           PreparedStatement preparedStatement = con.prepareStatement(query2);
            preparedStatement.setString(1,coupon_name);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {    
                String query3="update coupons set coupon_name=?,no_of_visits=?,total_shopping=?,off_price=? where coupon_name=?";
                PreparedStatement pst = con.prepareStatement(query3);
                pst.setString(1,coupon_name1);
                pst.setInt(2,no_of_visits);
                pst.setInt(3,total_shopping);
                pst.setInt(4,off_price);
                pst.setString(5,coupon_name);
                
                 
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"COUPON DETAILS UPDATED!!");
            }
            else
            {
            
                JOptionPane.showMessageDialog(this,"COUPON ENTERED NOT PRESENT IN DATABASE!!");  
      
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String couponname=cname.getText();
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query5="select * from coupons where coupon_name=?";
            
           PreparedStatement preparedStatement5 = con.prepareStatement(query5);
            preparedStatement5.setString(1,couponname);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement5.executeQuery();
            if(rs.next())
            {    
                String query6="DELETE from coupons where coupon_name=?";
                PreparedStatement pst1 = con.prepareStatement(query6);
                pst1.setString(1,couponname);
                //pst1.setString(2,name1);
            //preparedStatement.setString(2,pwd);
                pst1.executeUpdate();

                JOptionPane.showMessageDialog(this,"coupon DETAILS DELETED!!");
            }
            else
            {
            
                JOptionPane.showMessageDialog(this,"Coupon ENTERED NOT PRESENT IN DATABASE!!");  
      
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void OP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP3MouseClicked
        this.setVisible(false);
        new employee_details().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(COUPON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(COUPON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(COUPON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(COUPON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new COUPON().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OP1;
    private javax.swing.JPanel OP2;
    private javax.swing.JPanel OP3;
    private javax.swing.JPanel OP4;
    private javax.swing.JPanel OP5;
    private javax.swing.JComboBox<String> ccname;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cname1;
    private javax.swing.JTextField discount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable21;
    private javax.swing.JTextField no;
    private javax.swing.JTextField shop;
    // End of variables declaration//GEN-END:variables
}
