
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akshay Bali
 */
public class employee_details extends javax.swing.JFrame {

    /**
     * Creates new form employee_details
     */
    public employee_details() {
        initComponents();
        combo();
        combo1();
        //combo1();
    }
public void combo()
{
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from post";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                 des.addItem(type_r1.getString(2));   
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}
public void combo1()
{
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from post";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                 eet.addItem(type_r1.getString(2));   
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}

/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        OP1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        OP2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        OP3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        OP4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        OP5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        empmob = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        empname1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        sal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        des = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        eet = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        OP1.setBackground(new java.awt.Color(204, 0, 204));
        OP1.setForeground(new java.awt.Color(255, 255, 255));
        OP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP1MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRODUCT DETAILS.");

        javax.swing.GroupLayout OP1Layout = new javax.swing.GroupLayout(OP1);
        OP1.setLayout(OP1Layout);
        OP1Layout.setHorizontalGroup(
            OP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OP1Layout.setVerticalGroup(
            OP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP2.setBackground(new java.awt.Color(204, 0, 204));
        OP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP2MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PRINT DETAILS.");

        javax.swing.GroupLayout OP2Layout = new javax.swing.GroupLayout(OP2);
        OP2.setLayout(OP2Layout);
        OP2Layout.setHorizontalGroup(
            OP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8)
        );
        OP2Layout.setVerticalGroup(
            OP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP3.setBackground(new java.awt.Color(204, 0, 204));
        OP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP3MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EMPLOYEE DETAILS.");

        javax.swing.GroupLayout OP3Layout = new javax.swing.GroupLayout(OP3);
        OP3.setLayout(OP3Layout);
        OP3Layout.setHorizontalGroup(
            OP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP3Layout.setVerticalGroup(
            OP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP4.setBackground(new java.awt.Color(204, 0, 204));
        OP4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP4MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LOG OUT");

        javax.swing.GroupLayout OP4Layout = new javax.swing.GroupLayout(OP4);
        OP4.setLayout(OP4Layout);
        OP4Layout.setHorizontalGroup(
            OP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP4Layout.setVerticalGroup(
            OP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP5.setBackground(new java.awt.Color(204, 0, 204));
        OP5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP5MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADD COUPON.");

        javax.swing.GroupLayout OP5Layout = new javax.swing.GroupLayout(OP5);
        OP5.setLayout(OP5Layout);
        OP5Layout.setHorizontalGroup(
            OP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP5Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP5Layout.setVerticalGroup(
            OP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP5Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OP3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(OP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("EMPLOYEE DETAILS.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("EMPLOYEE MOBILE:");

        jButton8.setText("SEARCH DETAILS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "MOBILE NO.:", "SALARY:", "DESIGNATION", "DATE OF JOINING"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);

        jButton10.setText("Remove Selected Row");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("SALARY:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("EMPLOYEE NAME:");

        sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salActionPerformed(evt);
            }
        });

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("REMOVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("DESIGNATION:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("DATE OF JOINING:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("MOBILE NO.(ADD/UPDATE):");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("PASSWORD:");

        des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desActionPerformed(evt);
            }
        });

        jLabel2.setText("SEARCH BY TYPE:");

        eet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no value" }));
        eet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(empname1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                                .addComponent(jButton10))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(des, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(sal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jButton1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton3)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empmob, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eet, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(empmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addComponent(eet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseClicked
        this.setVisible(false);
        new PRODUCT_DETAILS().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP1MouseClicked

    private void OP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseEntered
        OP1.setOpaque(true);        // TODO add your handling code here:
        OP1.setForeground(Color.getHSBColor(51, 0, 51));
    }//GEN-LAST:event_OP1MouseEntered

    private void OP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseExited
        OP1.setForeground(Color.getHSBColor(204, 0, 204));
        OP1.setOpaque(false);        // TODO add your handling code here:
    }//GEN-LAST:event_OP1MouseExited

    private void OP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseClicked
        this.setVisible(false);
        new PRINTDETAILS().setVisible(true);
    }//GEN-LAST:event_OP2MouseClicked

    private void OP2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseEntered
        OP2.setOpaque(true);        // TODO add your handling code here:
        OP2.setForeground(Color.getHSBColor(51, 0, 51));
    }//GEN-LAST:event_OP2MouseEntered

    private void OP2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseExited
        OP2.setForeground(Color.getHSBColor(204, 0, 204));
        OP2.setOpaque(false);        // TODO add your handling code here:
    }//GEN-LAST:event_OP2MouseExited

    private void OP3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP3MouseEntered
        OP3.setOpaque(true);        // TODO add your handling code here:
        OP3.setForeground(Color.getHSBColor(51, 0, 51));
    }//GEN-LAST:event_OP3MouseEntered

    private void OP3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP3MouseExited
        OP3.setForeground(Color.getHSBColor(204, 0, 204));
        OP3.setOpaque(false);        // TODO add your handling code here:
    }//GEN-LAST:event_OP3MouseExited

    private void OP4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseClicked
        this.setVisible(false);
        new LOGIN().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP4MouseClicked

    private void OP4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseEntered
        OP4.setOpaque(true);        // TODO add your handling code here:
        OP4.setForeground(Color.getHSBColor(51, 0, 51));
    }//GEN-LAST:event_OP4MouseEntered

    private void OP4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseExited
          OP4.setForeground(Color.getHSBColor(204, 0, 204));
        OP4.setOpaque(false);        // TODO add your handling code here:

    }//GEN-LAST:event_OP4MouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String emp_mob=empmob.getText();
        String emp_type_t=(String) eet.getSelectedItem();
        String mobile;
        String salary;
        String des;
        String date=null;
char emp_type=emp_type_t.charAt(0);
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
         if((emp_type_t)!="no value")     
         {    
                String type_CHECK="select * from employee inner join person on employee.mobile=person.mobile where emp_type=?";
                PreparedStatement type_Statement= con.prepareStatement(type_CHECK);
                type_Statement.setString(1,String.valueOf(emp_type));
                ResultSet type_r3=type_Statement.executeQuery();

                while(type_r3.next())
                {
                    String post_t   =type_r3.getString("emp_type");
                    String emp_name    =type_r3.getString("name");
                    salary  =(type_r3.getString("salary"));
                    mobile  =type_r3.getString("mobile");
                   
                    
                    
                    
                    String type_CHECK9="select * from post where emp_type=?";//to display accountant instead of a
                    PreparedStatement type_Statement9= con.prepareStatement(type_CHECK9);
                    type_Statement9.setString(1,post_t);
                    ResultSet type_r39=type_Statement9.executeQuery();
                    if(type_r39.next())
                    {
                        des=type_r39.getString("emp_des");
                    }
                    else
                    {
                        des=null;
                    }
                   
                    
                    
                    
                    date=type_r3.getString("date_of_joining");
                    //p_type=ks.getString("p_type");
                    DefaultTableModel model1= (DefaultTableModel)jTable2.getModel();
                    model1.addRow(new Object[]{emp_mob,mobile,salary,des,date});
                }

            
        }
            else//if combo box has no value---searching by id
            {
                String NAME_CHECK4="select * from employee inner join person on employee.mobile=person.mobile where employee.mobile=?";
                PreparedStatement NAME_Statement4= con.prepareStatement(NAME_CHECK4);
                NAME_Statement4.setString(1,emp_mob);
                ResultSet ks4=NAME_Statement4.executeQuery();
                if(ks4.next())
                {
                   String emp_name=ks4.getString("name");
                    mobile=ks4.getString("mobile");
                    salary=ks4.getString("salary");

                    String post_t1=ks4.getString("emp_type");//convert a into accountant
                    String type_CHECK10="select * from post where emp_type=?";
                    PreparedStatement type_Statement10= con.prepareStatement(type_CHECK10);
                    type_Statement10.setString(1,post_t1);
                    ResultSet type_r310=type_Statement10.executeQuery();
                    if(type_r310.next())
                    {
                        des=type_r310.getString("emp_des");
                    }
                    else
                    {
                        des=null;
                    }

                    
                    
               
                    DefaultTableModel model2= (DefaultTableModel)jTable2.getModel();
                    model2.addRow(new Object[]{emp_mob,mobile,salary,des,date});
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"employee not present in database!!");
                }

                con.close();
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DefaultTableModel model= (DefaultTableModel)jTable2.getModel();
        //String row_no=no_row.getText();
        //int row=Integer.parseInt(row_no);
        String emp_id,p_count_s;
        int id,p_count;
        int selectedRowIndex = jTable2.getSelectedRow();
        emp_id = jTable2.getModel().getValueAt(selectedRowIndex,1).toString();
        //p_count_s=jTable2.getModel().getValueAt(selectedRowIndex,3).toString();
        //p_count=Integer.parseInt(p_count_s);
        //id=Integer.parseInt(emp_id);

        //System.out.print("p_id= "+p_id);
        model.removeRow(selectedRowIndex);
        //jTable1.revalidate();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query5="select * from print where p2=?";

            PreparedStatement preparedStatement5 = con.prepareStatement(query5);
            preparedStatement5.setString(1,emp_id);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement5.executeQuery();
            if(rs.next())
            {

                String query7="DELETE from print where p2=?";
                PreparedStatement pst2 = con.prepareStatement(query7);
                pst2.setString(1,emp_id);
                pst2.executeUpdate();

                JOptionPane.showMessageDialog(this,"EMPLOYEE DETAILS DELETED!!");
            }
            else
            {

                JOptionPane.showMessageDialog(this,"EMPLOYEE ID ENTERED NOT PRESENT IN DATABASE!!");

            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = empname1.getText();               //get employee name from text box
        int salary = Integer.parseInt(sal.getText());   //get SALARY from text box and CONVERT INTO INT
        int pass = Integer.parseInt(password.getText());
        String des1=(String) des.getSelectedItem();
        String contact = mobile.getText();
        String date_of = date.getText();
        

        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query1="select  * from employee where mobile=?";
            
           PreparedStatement preparedStatement = con.prepareStatement(query1);
            preparedStatement.setString(1,contact);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {    
                JOptionPane.showMessageDialog(this,"EMPLOYEE id already present!!");
            }
            else
            {
            String query = "insert into person(mobile,name)values(?,?)";
            PreparedStatement preparedStatement1 = con.prepareStatement(query);
            preparedStatement1.setString(1,contact);
            preparedStatement1.setString(2,name);
            preparedStatement1.executeUpdate();
            
                
        String query44 = "insert into employee(mobile,password,salary,emp_type,date_of_joining,customers_handled)values(?,?,?,?,?,?)";
            PreparedStatement preparedStatement144 = con.prepareStatement(query44);
            preparedStatement144.setString(1,contact);
            
            preparedStatement144.setInt(2,pass);
            preparedStatement144.setInt(3,salary);
            preparedStatement144.setString(4,String.valueOf(des1.charAt(0)));
            preparedStatement144.setString(5,date_of);
            preparedStatement144.setInt(6,0);
            preparedStatement144.executeUpdate();
            JOptionPane.showMessageDialog(this,"Employee Details added SUCCESSFULLY!!");  
            
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_desActionPerformed

    private void OP5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseClicked
                        this.setVisible(false);
                        new COUPON().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP5MouseClicked

    private void OP5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseEntered
        OP5.setOpaque(true);        // TODO add your handling code here:
        OP5.setForeground(Color.getHSBColor(51, 0, 51));
    }//GEN-LAST:event_OP5MouseEntered

    private void OP5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseExited
        OP5.setForeground(Color.getHSBColor(204, 0, 204));
        OP5.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP5MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String cno = mobile.getText();                               
        String name = empname1.getText();
        String sal1 = sal.getText();
         String date1 = date.getText();
        String des1 = (String) des.getSelectedItem();
        char emp_type=des1.charAt(0);
//String pwd = (jPasswordField1.getText());
        
       
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query2="select * from employee where mobile=?";
            
           PreparedStatement preparedStatement = con.prepareStatement(query2);
            preparedStatement.setString(1,cno);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {    
                String query3="update employee set mobile=?,salary=?,date_of_joining=?,emp_type=? where mobile=?";
                PreparedStatement pst = con.prepareStatement(query3);
                pst.setString(1,cno);
                pst.setString(2,sal1);
                pst.setString(3,date1);
                
                pst.setString(4,String.valueOf(emp_type));
                    pst.setString(5,cno);            
//preparedStatement.setString(2,pwd);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"ID DETAILS UPDATED!!");
            }
            else
            {
            
                JOptionPane.showMessageDialog(this,"LOGIN ID ENTERED NOT PRESENT IN DATABASE!!");  
      
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
        // TODO add your handling code here:
                                          

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void OP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP3MouseClicked
    }//GEN-LAST:event_OP3MouseClicked

    private void salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ccno = mobile.getText();
        //String name = jTextField4.getText();
        //String pwd = (jPasswordField1.getText());
        
       
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query5="select * from employee where mobile=?";
            
           PreparedStatement preparedStatement5 = con.prepareStatement(query5);
            preparedStatement5.setString(1,ccno);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement5.executeQuery();
            if(rs.next())
            {    
                String query6="DELETE from employee where mobile=?";
                PreparedStatement pst1 = con.prepareStatement(query6);
                pst1.setString(1,ccno);
                //pst1.setString(2,name1);
            //preparedStatement.setString(2,pwd);
                pst1.executeUpdate();

                JOptionPane.showMessageDialog(this,"ID DETAILS DELETED!!");
            }
            else
            {
            
                JOptionPane.showMessageDialog(this,"Employee ENTERED NOT PRESENT IN DATABASE!!");  
      
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }




    }//GEN-LAST:event_jButton3ActionPerformed

    private void eetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eetActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OP1;
    private javax.swing.JPanel OP2;
    private javax.swing.JPanel OP3;
    private javax.swing.JPanel OP4;
    private javax.swing.JPanel OP5;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> des;
    private javax.swing.JComboBox<String> eet;
    private javax.swing.JTextField empmob;
    private javax.swing.JTextField empname1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField password;
    private javax.swing.JTextField sal;
    // End of variables declaration//GEN-END:variables
}
