
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akshay Bali
 */
public class PRINTDETAILS extends javax.swing.JFrame {

    /**
     * Creates new form PRINTDETAILS
     */
    public PRINTDETAILS() {
        initComponents();
        combo();
        combo1();
        combo2();
        combo3();
    }
public void combo()
{    
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from product";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                ppname.addItem(type_r1.getString(3));   

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}
public void combo3()
{    
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from post";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                eet.addItem(type_r1.getString(2));   

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}

public void combo2()
{    
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from employee";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                empmob.addItem(type_r1.getString(2));   

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}

public void combo1()
{    
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from product_type";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                ppt.addItem(type_r1.getString(1));   

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        newpname1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        newpname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addstock = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pprice = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        OP1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        OP2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        OP4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        OP5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        OP6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        ppname = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        ppt = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        empmob = new javax.swing.JComboBox<>();
        eet = new javax.swing.JComboBox<>();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("PRODUCT NAME:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PRODUCT'S NEW NAME:");

        jButton4.setText("CHANGE NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CURRENTLY AVAILABLE STOCK/ADD STOCK:");

        jButton5.setText("REMOVE STOCK");

        jButton6.setText("ADD STOCK");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("PRODUCT PRICE:");

        jButton3.setText("UPDATE PRICE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("ADD NEW PRODUCT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        OP1.setBackground(new java.awt.Color(204, 0, 204));
        OP1.setForeground(new java.awt.Color(255, 255, 255));
        OP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP1MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADD NEW PRODUCT.");

        javax.swing.GroupLayout OP1Layout = new javax.swing.GroupLayout(OP1);
        OP1.setLayout(OP1Layout);
        OP1Layout.setHorizontalGroup(
            OP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OP1Layout.setVerticalGroup(
            OP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP2.setBackground(new java.awt.Color(204, 0, 204));
        OP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP2MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PRINT DETAILS.");

        javax.swing.GroupLayout OP2Layout = new javax.swing.GroupLayout(OP2);
        OP2.setLayout(OP2Layout);
        OP2Layout.setHorizontalGroup(
            OP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8)
        );
        OP2Layout.setVerticalGroup(
            OP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP4.setBackground(new java.awt.Color(204, 0, 204));
        OP4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP4MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LOG OUT");

        javax.swing.GroupLayout OP4Layout = new javax.swing.GroupLayout(OP4);
        OP4.setLayout(OP4Layout);
        OP4Layout.setHorizontalGroup(
            OP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP4Layout.setVerticalGroup(
            OP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP5.setBackground(new java.awt.Color(204, 0, 204));
        OP5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP5MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADD COUPON.");

        javax.swing.GroupLayout OP5Layout = new javax.swing.GroupLayout(OP5);
        OP5.setLayout(OP5Layout);
        OP5Layout.setHorizontalGroup(
            OP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP5Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP5Layout.setVerticalGroup(
            OP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP5Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP6.setBackground(new java.awt.Color(204, 0, 204));
        OP6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP6MouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EMPLOYEE DETAILS.");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout OP6Layout = new javax.swing.GroupLayout(OP6);
        OP6.setLayout(OP6Layout);
        OP6Layout.setHorizontalGroup(
            OP6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OP6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        OP6Layout.setVerticalGroup(
            OP6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP6Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PRINT DETAILS:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("PRODUCT NAME:");

        jButton2.setText("SEARCH DETAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PRODUCT TYPE", "UNIT PRICE", "AVAILABLE STOCK", "SOLD STOCK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("EMPLOYEE mobile:");

        jButton8.setText("SEARCH DETAILS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("PRINT DETAILS");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "MOBILE NO.:", "SALARY:", "DESIGNATION", "DATE OF JOINING"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee type", "employee-post"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton10.setText("Remove Selected Row");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("SHOW DETAILS");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        ppname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel13.setText("PRODUCT TYPE:");

        ppt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no value" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("EMPLOYEE TYPE:");

        empmob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        eet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no value" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(jLabel1)
                                                    .addGap(123, 123, 123))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(ppname, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel13)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(ppt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE)))
                                            .addComponent(jButton2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(empmob, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(14, 14, 14)
                                        .addComponent(eet, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)
                        .addComponent(ppname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(empmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseEntered
        OP1.setOpaque(true);        // TODO add your handling code here:
        OP1.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_OP1MouseEntered

    private void OP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseExited
        OP1.setForeground(Color.getHSBColor(204, 0, 204));
        OP1.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP1MouseExited

    private void OP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseClicked
   String emp_type;
   String emp_des;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            
            String type_CHECK="select * from post";    
           PreparedStatement type_Statement= con.prepareStatement(type_CHECK);
            //type_Statement.setString(1,p_name);
            ResultSet type_r=type_Statement.executeQuery();               
            while(type_r.next())
              {
                emp_type=type_r.getString("emp_type");
                emp_des=type_r.getString("emp_des");
               
                DefaultTableModel model= (DefaultTableModel)jTable3.getModel();
                model.addRow(new Object[]{emp_type,emp_des});       
              }
                       
           
        con.close();
                      
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }

        
        
    }//GEN-LAST:event_OP2MouseClicked

    private void OP2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseEntered
        OP2.setOpaque(true);        // TODO add your handling code here:
        OP2.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_OP2MouseEntered

    private void OP2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseExited
        OP2.setForeground(Color.getHSBColor(204, 0, 204));
        OP2.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP2MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String p_name=newpname.getText();
        int p_price=Integer.parseInt(pprice.getText());
        int available_stock=Integer.parseInt(addstock.getText());

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query1="select * from product where p_name=?";

            PreparedStatement preparedStatement = con.prepareStatement(query1);
            preparedStatement.setString(1,p_name);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this,"Product already present in database!!");
            }
            else
            {
                String query = "insert into product(p_name,p_price,available_stock,sold_stock) values(?,?,?,?)";
                PreparedStatement preparedStatement1 = con.prepareStatement(query);
                preparedStatement1.setString(1,p_name);
                preparedStatement1.setInt(2,p_price);
                preparedStatement1.setInt(3,available_stock);
                preparedStatement1.setInt(4,0);

                // execute insert SQL stetement
                preparedStatement1.executeUpdate();
                JOptionPane.showMessageDialog(this,"PRODUCT ADDED SUCCESSFULLY!!");

            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String p_name=(String) ppname.getSelectedItem();
        String p_price;
        String available_stock;
        String sold_stock;
        String p_type_t=(String) ppt.getSelectedItem();
        char p_type=p_type_t.charAt(0);
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            if(p_type_t!="no value")
            {
                String type_CHECK="select * from product where p_type=?";
                PreparedStatement type_Statement= con.prepareStatement(type_CHECK);
                type_Statement.setString(1,String.valueOf(p_type));
                ResultSet type_r=type_Statement.executeQuery();

                while(type_r.next())
                {
                    p_name=type_r.getString("p_name");
                    p_price=type_r.getString("p_price");
                    available_stock=type_r.getString("available_stock");
                    sold_stock=type_r.getString("sold_stock");
                    DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
                    model.addRow(new Object[]{p_name,p_type,p_price,available_stock,sold_stock});
                }
            }
            else
            {
                String NAME_CHECK="select * from product where p_name=?";
                PreparedStatement NAME_Statement= con.prepareStatement(NAME_CHECK);
                NAME_Statement.setString(1,p_name);
                ResultSet ks=NAME_Statement.executeQuery();
                if(ks.next())
                {
                    p_name=ks.getString("p_name");
                    p_price=ks.getString("p_price");
                    available_stock=ks.getString("available_stock");
                    sold_stock=ks.getString("sold_stock");
                    DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
                    model.addRow(new Object[]{p_name,p_type,p_price,available_stock,sold_stock});
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Product not present in database!!");
                }

                con.close();
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String p_name=newpname.getText();
        int p_price=Integer.parseInt(pprice.getText());
        int add_stock=Integer.parseInt(addstock.getText());
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query2="select * from product where p_name=?";

            PreparedStatement preparedStatement = con.prepareStatement(query2);
            preparedStatement.setString(1,p_name);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {
                String query3="update product set p_name=?,p_price=?,available_stock=available_stock+? where p_name=?";
                PreparedStatement pst = con.prepareStatement(query3);
                pst.setString(1,p_name);
                pst.setInt(2,p_price);
                pst.setInt(3,add_stock);
                pst.setString(4,p_name);
                //preparedStatement.setString(2,pwd);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"PRODUCT DETAILS UPDATED!!");
            }
            else
            {

                JOptionPane.showMessageDialog(this,"PRODUCT ENTERED NOT PRESENT IN DATABASE!!");

            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String emp_mob=(String)empmob.getSelectedItem();
        String emp_type_t=(String) eet.getSelectedItem();
        String mobile;
        String salary;
        String des;
        String date=null;
char emp_type=emp_type_t.charAt(0);
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
         if((emp_type_t)!="no value")     
         {    
                String type_CHECK="select * from employee inner join person on employee.mobile=person.mobile where emp_type=?";
                PreparedStatement type_Statement= con.prepareStatement(type_CHECK);
                type_Statement.setString(1,String.valueOf(emp_type));
                ResultSet type_r3=type_Statement.executeQuery();

                while(type_r3.next())
                {
                    String post_t   =type_r3.getString("emp_type");
                    String emp_name    =type_r3.getString("name");
                    salary  =(type_r3.getString("salary"));
                    mobile  =type_r3.getString("mobile");
                   
                    
                    
                    
                    String type_CHECK9="select * from post where emp_type=?";//to display accountant instead of a
                    PreparedStatement type_Statement9= con.prepareStatement(type_CHECK9);
                    type_Statement9.setString(1,post_t);
                    ResultSet type_r39=type_Statement9.executeQuery();
                    if(type_r39.next())
                    {
                        des=type_r39.getString("emp_des");
                    }
                    else
                    {
                        des=null;
                    }
                   
                    
                    
                    
                    date=type_r3.getString("date_of_joining");
                    //p_type=ks.getString("p_type");
                    DefaultTableModel model1= (DefaultTableModel)jTable2.getModel();
                    model1.addRow(new Object[]{emp_name,emp_mob,salary,des,date});
               String q="insert into print (p1,p2,p3,p4,p5) values(?,?,?,?,?)";
 PreparedStatement p1 = con.prepareStatement(q);
            p1.setString(1,emp_name);
            p1.setString(2,mobile);
            p1.setString(3,salary);
            p1.setString(4,des);
            p1.setString(5,date);
            p1.executeUpdate();

                }

            
        }
            else//if combo box has no value---searching by id
            {
                String NAME_CHECK4="select * from employee inner join person on employee.mobile=person.mobile where employee.mobile=?";
                PreparedStatement NAME_Statement4= con.prepareStatement(NAME_CHECK4);
                NAME_Statement4.setString(1,emp_mob);
                ResultSet ks4=NAME_Statement4.executeQuery();
                if(ks4.next())
                {
                   String emp_name=ks4.getString("name");
                    mobile=ks4.getString("mobile");
                    salary=ks4.getString("salary");

                    String post_t1=ks4.getString("emp_type");//convert a into accountant
                    String type_CHECK10="select * from post where emp_type=?";
                    PreparedStatement type_Statement10= con.prepareStatement(type_CHECK10);
                    type_Statement10.setString(1,post_t1);
                    ResultSet type_r310=type_Statement10.executeQuery();
                    if(type_r310.next())
                    {
                        des=type_r310.getString("emp_des");
                    }
                    else
                    {
                        des=null;
                    }

                    
                    
               
                    DefaultTableModel model2= (DefaultTableModel)jTable2.getModel();
                    model2.addRow(new Object[]{emp_mob,mobile,salary,des,date});
               String q="insert into print (p1,p2,p3,p4,p5) values(?,?,?,?,?)";
 PreparedStatement p1 = con.prepareStatement(q);
            p1.setString(1,emp_name);
            p1.setString(2,emp_mob);
            p1.setString(3,salary);
            p1.setString(4,des);
            p1.setString(5,date);
            p1.executeUpdate();
           
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"employee not present in database!!");
                }

                con.close();
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
           com.itextpdf.text.Document document = new com.itextpdf.text.Document();
      try
      {
       PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("C:\\akshay\\mega-mart\\employeeDetails.pdf"));
        int i=0;     
   document.open();
          document.addTitle("EMPLOYEE DETAILS");
          //addEmptyLine(preface,8);
          Paragraph preface = new Paragraph();
             
            preface.add(new Paragraph(" "));
             
          preface.add(new Paragraph("                                                            MEGAMART EMPLOYEE DETAILS"));
          document.add(preface);
           PdfPTable table = new PdfPTable(5); // 3 columns.
          table.setWidthPercentage(100); //Width 100%
          table.setSpacingBefore(10f); //Space before table
          table.setSpacingAfter(10f); //Space after table

          //Set Column widths
          float[] columnWidths = {1f, 1f, 1f, 1f, 1f};
          table.setWidths(columnWidths);


          
          
          
          PdfPCell cell1 = new PdfPCell(new Paragraph("Name"));
          cell1.setBorderColor(BaseColor.BLACK);
          cell1.setPaddingLeft(10);
          cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell1.setVerticalAlignment(Element.ALIGN_MIDDLE);

          PdfPCell cell2 = new PdfPCell(new Paragraph("Contact"));
          cell2.setBorderColor(BaseColor.BLACK);
          cell2.setPaddingLeft(10);
          cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell2.setVerticalAlignment(Element.ALIGN_MIDDLE);

          PdfPCell cell3 = new PdfPCell(new Paragraph("Salary"));
          cell3.setBorderColor(BaseColor.BLACK);
          cell3.setPaddingLeft(10);
          cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell3.setVerticalAlignment(Element.ALIGN_MIDDLE);
          
          PdfPCell cell4 = new PdfPCell(new Paragraph("Designation"));
          cell4.setBorderColor(BaseColor.BLACK);
          cell4.setPaddingLeft(10);
          cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell4.setVerticalAlignment(Element.ALIGN_MIDDLE);

          PdfPCell cell5 = new PdfPCell(new Paragraph("Date of Joining"));
          cell5.setBorderColor(BaseColor.BLACK);
          cell5.setPaddingLeft(10);
          cell5.setHorizontalAlignment(Element.ALIGN_CENTER);
          cell5.setVerticalAlignment(Element.ALIGN_MIDDLE);

          
          table.addCell(cell1);
          table.addCell(cell2);
          table.addCell(cell3);
          table.addCell(cell4);
          table.addCell(cell5);
          
        try{
                        Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");

            PreparedStatement pst,pst1;
            String sql ="SELECT * FROM print;";
            pst = con.prepareStatement(sql);
            //NAME_Statement.setString(1,p_name);
            ResultSet rs = pst.executeQuery(); // without arguments
            
            while(rs.next())  
            {
  
                PdfPCell cellI = new PdfPCell(new Paragraph(rs.getString("p1")));
                cellI.setBorderColor(BaseColor.BLACK);
                cellI.setPaddingLeft(10);
                cellI.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellI.setVerticalAlignment(Element.ALIGN_MIDDLE);
                
                PdfPCell cellJ = new PdfPCell(new Paragraph(rs.getString("p2")));
                cellJ.setBorderColor(BaseColor.BLACK);
                cellJ.setPaddingLeft(10);
                cellJ.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellJ.setVerticalAlignment(Element.ALIGN_MIDDLE);
                
                PdfPCell cellK = new PdfPCell(new Paragraph(rs.getString("p3")));
                cellK.setBorderColor(BaseColor.BLACK);
                cellK.setPaddingLeft(10);
                cellK.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellK.setVerticalAlignment(Element.ALIGN_MIDDLE);
                
                PdfPCell cellM = new PdfPCell(new Paragraph(rs.getString("p4")));
                cellM.setBorderColor(BaseColor.BLACK);
                cellM.setPaddingLeft(10);
                cellM.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellM.setVerticalAlignment(Element.ALIGN_MIDDLE);

                PdfPCell cellN = new PdfPCell(new Paragraph(rs.getString("p5")));
                cellN.setBorderColor(BaseColor.BLACK);
                cellN.setPaddingLeft(10);
                cellN.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellN.setVerticalAlignment(Element.ALIGN_MIDDLE);

                table.addCell(cellI);
                table.addCell(cellJ);
                table.addCell(cellK);
                table.addCell(cellM);
                table.addCell(cellN);
            }
            
            document.add(table);
//String query61="DELETE from print";
  //              PreparedStatement pst11 = con.prepareStatement(query61);
    //            pst11.executeUpdate();
                
            
             }
            
        
        catch(Exception e){
            System.out.println(e);
        }
        
          //document.add(table);

          document.close();
          writer.close();
                           
          JOptionPane.showMessageDialog(this,"Summary Generated Successfully");  
      } catch (Exception e)
      {
          e.printStackTrace();
           JOptionPane.showMessageDialog(this,e);  
      }
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
DefaultTableModel model= (DefaultTableModel)jTable2.getModel();
//String row_no=no_row.getText();
//int row=Integer.parseInt(row_no);
String emp_id,p_count_s;
int id,p_count;
int selectedRowIndex = jTable2.getSelectedRow();
emp_id = jTable2.getModel().getValueAt(selectedRowIndex,1).toString();
//p_count_s=jTable2.getModel().getValueAt(selectedRowIndex,3).toString();
//p_count=Integer.parseInt(p_count_s);
//id=Integer.parseInt(emp_id);

//System.out.print("p_id= "+p_id);
model.removeRow(selectedRowIndex);
//jTable1.revalidate();
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query5="select * from print where p2=?";
            
           PreparedStatement preparedStatement5 = con.prepareStatement(query5);
            preparedStatement5.setString(1,emp_id);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement5.executeQuery();
            if(rs.next())
            {    
             
            String query7="DELETE from print where p2=?";
                PreparedStatement pst2 = con.prepareStatement(query7);
                pst2.setString(1,emp_id);
                pst2.executeUpdate();

                JOptionPane.showMessageDialog(this,"EMPLOYEE DETAILS DELETED!!");    
            }
            else
            {
            
                JOptionPane.showMessageDialog(this,"EMPLOYEE ID ENTERED NOT PRESENT IN DATABASE!!");  
      
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void OP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseClicked
                        this.setVisible(false);
                        new PRODUCT_DETAILS().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP1MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
   String emp_type;
   String emp_des;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            
            String type_CHECK="select * from post";    
           PreparedStatement type_Statement= con.prepareStatement(type_CHECK);
            //type_Statement.setString(1,p_name);
            ResultSet type_r=type_Statement.executeQuery();               
            while(type_r.next())
              {
                emp_type=type_r.getString("emp_type");
                emp_des=type_r.getString("emp_des");
               
                DefaultTableModel model= (DefaultTableModel)jTable3.getModel();
                model.addRow(new Object[]{emp_type,emp_des});       
              }
                       
           
        con.close();
                      
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void OP4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseEntered
        OP4.setOpaque(true);        // TODO add your handling code here:
        OP4.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_OP4MouseEntered

    private void OP4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseExited
        OP4.setForeground(Color.getHSBColor(204, 0, 204));
        OP4.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP4MouseExited

    private void OP4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseClicked
                        this.setVisible(false);
                        new LOGIN().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP4MouseClicked

    private void OP5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseClicked
                        this.setVisible(false);
                        new COUPON().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP5MouseClicked

    private void OP5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseEntered
        OP5.setOpaque(true);        // TODO add your handling code here:
        OP5.setForeground(Color.getHSBColor(51, 0, 51));
    }//GEN-LAST:event_OP5MouseEntered

    private void OP5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseExited
        OP5.setForeground(Color.getHSBColor(204, 0, 204));
        OP5.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP5MouseExited

    private void OP6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP6MouseClicked
                        this.setVisible(false);
                        new employee_details().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP6MouseClicked

    private void OP6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP6MouseEntered
        OP6.setOpaque(true);        // TODO add your handling code here:
        OP6.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_OP6MouseEntered

    private void OP6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP6MouseExited
        OP6.setForeground(Color.getHSBColor(204, 0, 204));
        OP6.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP6MouseExited

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINTDETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINTDETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINTDETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINTDETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINTDETAILS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OP1;
    private javax.swing.JPanel OP2;
    private javax.swing.JPanel OP4;
    private javax.swing.JPanel OP5;
    private javax.swing.JPanel OP6;
    private javax.swing.JTextField addstock;
    private javax.swing.JComboBox<String> eet;
    private javax.swing.JComboBox<String> empmob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField newpname;
    private javax.swing.JTextField newpname1;
    private javax.swing.JComboBox<String> ppname;
    private javax.swing.JTextField pprice;
    private javax.swing.JComboBox<String> ppt;
    // End of variables declaration//GEN-END:variables
}
