
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akshay Bali
 */
public class PRODUCT_DETAILS extends javax.swing.JFrame {

    /**
     * Creates new form page3
     */
    public PRODUCT_DETAILS() {
        initComponents();
        combo();
        combo3();
        combo4();
    }
public void combo()
{    
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from product";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                ppname.addItem(type_r1.getString(3));   

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}

public void combo3()
{    
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from product_type";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                ppt.addItem(type_r1.getString(2));   

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}
public void combo4()
{    
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3307/megamart","root","");
            String type_CHECK1="select * from product_type";
            PreparedStatement type_Statement1= con.prepareStatement(type_CHECK1);
            
            ResultSet type_r1=type_Statement1.executeQuery();
            while(type_r1.next())
            //if(emp_name.equalsIgnoreCase("c") || p_name.equalsIgnoreCase("G"))
            {
                pt.addItem(type_r1.getString(2));   

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        OP1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        OP2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        OP3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        OP4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        OP5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        OP6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addstock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        newpname = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        ppname = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        ppt = new javax.swing.JComboBox<>();
        oldpname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pt = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        OP1.setBackground(new java.awt.Color(204, 0, 204));
        OP1.setForeground(new java.awt.Color(255, 255, 255));
        OP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP1MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADD NEW PRODUCT.");

        javax.swing.GroupLayout OP1Layout = new javax.swing.GroupLayout(OP1);
        OP1.setLayout(OP1Layout);
        OP1Layout.setHorizontalGroup(
            OP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        OP1Layout.setVerticalGroup(
            OP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP2.setBackground(new java.awt.Color(204, 0, 204));
        OP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP2MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PRINT DETAILS.");

        javax.swing.GroupLayout OP2Layout = new javax.swing.GroupLayout(OP2);
        OP2.setLayout(OP2Layout);
        OP2Layout.setHorizontalGroup(
            OP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8)
        );
        OP2Layout.setVerticalGroup(
            OP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP3.setBackground(new java.awt.Color(204, 0, 204));
        OP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP3MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PRODUCTS DETAILS.");

        javax.swing.GroupLayout OP3Layout = new javax.swing.GroupLayout(OP3);
        OP3.setLayout(OP3Layout);
        OP3Layout.setHorizontalGroup(
            OP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP3Layout.setVerticalGroup(
            OP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP4.setBackground(new java.awt.Color(204, 0, 204));
        OP4.setForeground(new java.awt.Color(255, 255, 255));
        OP4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP4MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LOG OUT");

        javax.swing.GroupLayout OP4Layout = new javax.swing.GroupLayout(OP4);
        OP4.setLayout(OP4Layout);
        OP4Layout.setHorizontalGroup(
            OP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP4Layout.setVerticalGroup(
            OP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP5.setBackground(new java.awt.Color(204, 0, 204));
        OP5.setForeground(new java.awt.Color(255, 255, 255));
        OP5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP5MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADD COUPON.");

        javax.swing.GroupLayout OP5Layout = new javax.swing.GroupLayout(OP5);
        OP5.setLayout(OP5Layout);
        OP5Layout.setHorizontalGroup(
            OP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP5Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP5Layout.setVerticalGroup(
            OP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP5Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        OP6.setBackground(new java.awt.Color(204, 0, 204));
        OP6.setForeground(new java.awt.Color(255, 255, 255));
        OP6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OP6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OP6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OP6MouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("EMPLOYEE DETAILS.");

        javax.swing.GroupLayout OP6Layout = new javax.swing.GroupLayout(OP6);
        OP6.setLayout(OP6Layout);
        OP6Layout.setHorizontalGroup(
            OP6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP6Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OP6Layout.setVerticalGroup(
            OP6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP6Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OP3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(OP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ADD NEW PRODUCT/UPDATE EXISTING");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CURRENTLY AVAILABLE STOCK/ADD STOCK:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("PRODUCT NAME:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("PRODUCT NAME:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("PRODUCT PRICE:");

        jButton1.setText("ADD NEW PRODUCT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SEARCH DETAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PRODUCT TYPE", "UNIT PRICE", "AVAILABLE STOCK", "SOLD STOCK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton3.setText("UPDATE PRICE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PRODUCT'S NEW NAME:");

        jButton4.setText("CHANGE NAME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("REMOVE STOCK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("ADD STOCK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("CLEAR ROW");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        ppname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        ppname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppnameActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("PRODUCT TYPE:");

        ppt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no value" }));

        oldpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpnameActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("product_type:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ppname, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ppt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(oldpname, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(newpname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(pprice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(addstock, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton6))))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton7)
                    .addComponent(ppname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(oldpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(pt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseEntered
        OP1.setOpaque(true);        // TODO add your handling code here:
        OP1.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_OP1MouseEntered

    private void OP2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseEntered
        OP2.setOpaque(true);        // TODO add your handling code here:
        OP2.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_OP2MouseEntered

    private void OP3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP3MouseEntered
        OP3.setOpaque(true);        // TODO add your handling code here:
        OP3.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_OP3MouseEntered

    private void OP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP1MouseExited
        OP1.setForeground(Color.getHSBColor(204, 0, 204));
        OP1.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP1MouseExited

    private void OP2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseExited
        OP2.setForeground(Color.getHSBColor(204, 0, 204));
        OP2.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP2MouseExited

    private void OP3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP3MouseExited
        OP3.setForeground(Color.getHSBColor(204, 0, 204));
        OP3.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP3MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String p_name=(String) ppname.getSelectedItem();
        String p_price;
        String available_stock;
        String sold_stock;
        String p_type_t=(String) ppt.getSelectedItem();
        char p_type=p_type_t.charAt(0);
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            if(p_type_t !="no value")
            {
            String type_CHECK="select * from product where p_type=?";    
           PreparedStatement type_Statement= con.prepareStatement(type_CHECK);
           
            type_Statement.setString(1,String.valueOf(p_type));
            ResultSet type_r=type_Statement.executeQuery();   
            
            
            while(type_r.next())
              {
                p_name=type_r.getString("p_name");
                p_price=type_r.getString("p_price");
                available_stock=type_r.getString("available_stock");
                sold_stock=type_r.getString("sold_stock");
                DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
                model.addRow(new Object[]{p_name,p_type_t,p_price,available_stock,sold_stock});       
              }
            
                    
            }
            else
            {
            String NAME_CHECK="select * from product where p_name=?";    
           PreparedStatement NAME_Statement= con.prepareStatement(NAME_CHECK);
            NAME_Statement.setString(1,p_name);
            ResultSet ks=NAME_Statement.executeQuery();
            if(ks.next())
            {    
                p_name=ks.getString("p_name");
                p_price=ks.getString("p_price");
                available_stock=ks.getString("available_stock");
                sold_stock=ks.getString("sold_stock");
                p_type_t=ks.getString("p_type");
                p_type=p_type_t.charAt(0);         
                //p_type_t=type_r.getString("p_type");
                String q="select * from product_type where product_type=?";
            PreparedStatement t= con.prepareStatement(q);          
            t.setString(1,String.valueOf(p_type));
            ResultSet type_r12=t.executeQuery();   
                          if(type_r12.next())
                          {
                            p_type_t=type_r12.getString("product_type_name");
                          }
      
                
                DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
                model.addRow(new Object[]{p_name,p_type_t,p_price,available_stock,sold_stock});       
            } 
            else
            {
            JOptionPane.showMessageDialog(this,"Product not present in database!!");
            }
        
        con.close();
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
        // TODO add your handling code here:
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String p_name=oldpname.getText();
int p_price=Integer.parseInt(pprice.getText());
int available_stock=Integer.parseInt(addstock.getText());
char p_type=((String)pt.getSelectedItem()).charAt(0);
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query1="select * from product where p_name=?";
            
           PreparedStatement preparedStatement = con.prepareStatement(query1);
            preparedStatement.setString(1,p_name);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {    
                JOptionPane.showMessageDialog(this,"Product already present in database!!");
            }
            else
            {
            String query = "insert into product(p_name,p_price,available_stock,sold_stock,p_type) values(?,?,?,?,?)";
            PreparedStatement preparedStatement1 = con.prepareStatement(query);
            preparedStatement1.setString(1,p_name);
            preparedStatement1.setInt(2,p_price);
            preparedStatement1.setInt(3,available_stock);
            preparedStatement1.setInt(4,0);
             preparedStatement1.setString(5,String.valueOf(p_type));
            
            
            // execute insert SQL stetement
            preparedStatement1.executeUpdate();
            JOptionPane.showMessageDialog(this,"PRODUCT ADDED SUCCESSFULLY!!");  
            
            }
con.close();             
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
       
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String p_name=oldpname.getText();
        int p_price=Integer.parseInt(pprice.getText());
        //int add_stock=Integer.parseInt(addstock.getText());
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query2="select * from product where p_name=?";
            
           PreparedStatement preparedStatement = con.prepareStatement(query2);
            preparedStatement.setString(1,p_name);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {    
                String query3="update product set p_price=? where p_name=?";
                PreparedStatement pst = con.prepareStatement(query3);
                pst.setInt(1,p_price);
                
                //pst.setInt(3,add_stock);
                pst.setString(2,p_name);
            //preparedStatement.setString(2,pwd);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"PRODUCT DETAILS UPDATED!!");
            }
            else
            {
            
                JOptionPane.showMessageDialog(this,"PRODUCT ENTERED NOT PRESENT IN DATABASE!!");  
      
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
String p_id;
int selectedRowIndex = jTable1.getSelectedRow();
//p_id = jTable1.getModel().getValueAt(selectedRowIndex,1).toString();
model.removeRow(selectedRowIndex);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void OP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP2MouseClicked
                        
                        this.setVisible(false);
                        new PRINTDETAILS().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String old_name = oldpname.getText();
        String new_name = newpname.getText();
        
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query2="select * from product where p_name=?";
            
           PreparedStatement preparedStatement = con.prepareStatement(query2);
            preparedStatement.setString(1,old_name);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {    
                String query3="update product set p_name=? where p_name=?";
                PreparedStatement pst = con.prepareStatement(query3);
                pst.setString(1,new_name);
                pst.setString(2,old_name);
            //preparedStatement.setString(2,pwd);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"PRODUCT DETAILS UPDATED!!");
            }
            else
            {
            
                JOptionPane.showMessageDialog(this,"PRODUCT ENTERED NOT PRESENT IN DATABASE!!");  
      
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String p_name=oldpname.getText();
int remove=Integer.parseInt(addstock.getText());
int available_stock;//=Integer.parseInt(addstock.getText());

        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query1="select * from product where p_name=?";
            
           PreparedStatement preparedStatement = con.prepareStatement(query1);
            preparedStatement.setString(1,p_name);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {    
                available_stock=rs.getInt("available_stock");
                if(available_stock>remove)
                {
                String query3="update product set available_stock=available_stock-? where p_name=?";
                PreparedStatement pst = con.prepareStatement(query3);
                pst.setInt(1,remove);
                pst.setString(2,p_name);
            //preparedStatement.setString(2,pwd);
                pst.executeUpdate();
                }               
               else
                {
                JOptionPane.showMessageDialog(this,"Entered count exceeds available count!!");
                
                }
            }
            
con.close();             
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String p_name=oldpname.getText();
int remove=Integer.parseInt(addstock.getText());
int available_stock;//=Integer.parseInt(addstock.getText());

        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/megamart","root","");
            //Statement stmt=con.createStatement();
            //atement stmt1=con.createStatement();
            String query1="select * from product where p_name=?";
            
           PreparedStatement preparedStatement = con.prepareStatement(query1);
            preparedStatement.setString(1,p_name);
            //preparedStatement.setString(2,pwd);
            ResultSet rs=preparedStatement.executeQuery();
            if(rs.next())
            {    
                available_stock=rs.getInt("available_stock");
                String query3="update product set available_stock=available_stock+? where p_name=?";
                PreparedStatement pst = con.prepareStatement(query3);
                pst.setInt(1,remove);
                pst.setString(2,p_name);
            //preparedStatement.setString(2,pwd);
                pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Product details apdated successfully!!");    
            }
            
con.close();             
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,e);  
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void OP4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseEntered
        OP4.setOpaque(true);        // TODO add your handling code here:
        OP4.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_OP4MouseEntered

    private void OP4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseExited
        OP4.setForeground(Color.getHSBColor(204, 0, 204));
        OP4.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP4MouseExited

    private void OP4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP4MouseClicked
                        this.setVisible(false);
                        new LOGIN().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP4MouseClicked

    private void OP5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseClicked
                        this.setVisible(false);
                        new COUPON().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP5MouseClicked

    private void OP5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseEntered
        OP5.setOpaque(true);        // TODO add your handling code here:
        OP5.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_OP5MouseEntered

    private void OP5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP5MouseExited
        OP5.setForeground(Color.getHSBColor(204, 0, 204));
        OP5.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP5MouseExited

    private void oldpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpnameActionPerformed

    private void OP6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP6MouseClicked
                        this.setVisible(false);
                        new employee_details().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OP6MouseClicked

    private void OP6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP6MouseEntered
        OP6.setOpaque(true);        // TODO add your handling code here:
        OP6.setForeground(Color.getHSBColor(51, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_OP6MouseEntered

    private void OP6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OP6MouseExited
        OP6.setForeground(Color.getHSBColor(204, 0, 204));
        OP6.setOpaque(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_OP6MouseExited

    private void ppnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRODUCT_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRODUCT_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRODUCT_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRODUCT_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRODUCT_DETAILS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OP1;
    private javax.swing.JPanel OP2;
    private javax.swing.JPanel OP3;
    private javax.swing.JPanel OP4;
    private javax.swing.JPanel OP5;
    private javax.swing.JPanel OP6;
    private javax.swing.JTextField addstock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField newpname;
    private javax.swing.JTextField oldpname;
    private javax.swing.JComboBox<String> ppname;
    private javax.swing.JTextField pprice;
    private javax.swing.JComboBox<String> ppt;
    private javax.swing.JComboBox<String> pt;
    // End of variables declaration//GEN-END:variables
}
